export const LeaguesEnum = {
  BRASILEIRAO_SERIE_A: 71,
  BRASILEIRAO_SERIE_B: 71,
  PREMIER_LEAGUE: 71,
  LA_LIGA: 71,
};

export const TeamIdEnum = {
  ATHLETICO_PARANAENSE: 134,
  ATLETICO_GOIANENSE: 144,
  ATLETICO_MG: 1062,
  BAHIA: 118,
  BOTAFOGO: 120,
  BRAGANTINO: 794,
  CORINTHIANS: 131,
  CRICIUMA: 140,
  CRUZEIRO: 135,
  CUIABA: 1193,
  FLAMENGO: 127,
  FLUMINENSE: 124,
  FORTALEZA: 154,
  GREMIO: 130,
  INTERNACIONAL: 119,
  JUVENTUDE: 152,
  PALMEIRAS: 121,
  SAO_PAULO: 126,
  VASCO_DA_GAMA: 133,
  VITORIA: 136,
};

export const BookmakersEnum = {
  BET_365: 8,
  BETFAIR: 3,
};

export const teamNameMap = {
  [TeamIdEnum.ATHLETICO_PARANAENSE]: "Athletico Paranaense",
  [TeamIdEnum.ATLETICO_GOIANENSE]: "Atletico-GO",
  [TeamIdEnum.ATLETICO_MG]: "Atletico-MG",
  [TeamIdEnum.BAHIA]: "Bahia",
  [TeamIdEnum.BOTAFOGO]: "Botafogo",
  [TeamIdEnum.BRAGANTINO]: "Bragantino",
  [TeamIdEnum.CORINTHIANS]: "Corintians",
  [TeamIdEnum.CRICIUMA]: "Criciuma",
  [TeamIdEnum.CRUZEIRO]: "Cruzeiro",
  [TeamIdEnum.CUIABA]: "Cuiabá",
  [TeamIdEnum.FLAMENGO]: "Flamengo",
  [TeamIdEnum.FLUMINENSE]: "Fluminense",
  [TeamIdEnum.FORTALEZA]: "Fortaleza",
  [TeamIdEnum.GREMIO]: "Gremio",
  [TeamIdEnum.INTERNACIONAL]: "Internacional",
  [TeamIdEnum.JUVENTUDE]: "Juventude",
  [TeamIdEnum.PALMEIRAS]: "Palmeiras",
  [TeamIdEnum.SAO_PAULO]: "São Paulo",
  [TeamIdEnum.VASCO_DA_GAMA]: "Vasco da Gama",
  [TeamIdEnum.VITORIA]: "Vitória",
};

export const MatchStatisticsTypeEnum = {
  SHOTS_ON_GOAL: "Shots on Goal",
  SHOTS_OFF_GOAL: "Shots off Goal",
  TOTAL_SHOTS: "Total Shots",
  BLOCKED_SHOTS: "Blocked Shots",
  SHOTS_INSIDEBOX: "Shots insidebox",
  FOULS: "Fouls",
  CORNER_KICKS: "Corner Kicks",
  OFFSIDES: "Offsides",
  BALL_POSSESSION: "Ball Possession",
  YELLOW_CARDS: "Yellow Cards",
  RED_CARDS: "Red Cards",
  GOALKEEPER_SAVES: "Goalkeeper Saves",
  TOTAL_PASSES: "Total passes",
  PASSES_ACCURATE: "Passes accurate",
  PASSES_PERCENTAGE: "Passes %",
};

// export const matchStatisticTypeMap = {
//   [MatchStatisticsTypeEnum.SHOTS_ON_GOAL]: "Chutes ao gol",
//   [MatchStatisticsTypeEnum.SHOTS_OFF_GOAL]: "Chutes fora do gol",
//   [MatchStatisticsTypeEnum.TOTAL_SHOTS]: "Finalizações",
//   [MatchStatisticsTypeEnum.BLOCKED_SHOTS]: "Chutes bloqueados",
//   [MatchStatisticsTypeEnum.FOULS]: "Faltas",
//   [MatchStatisticsTypeEnum.CORNER_KICKS]: "Escanteios",
//   [MatchStatisticsTypeEnum.OFFSIDES]: "Impedimentos",
//   [MatchStatisticsTypeEnum.BALL_POSSESSION]: "Posse de bola",
//   [MatchStatisticsTypeEnum.YELLOW_CARDS]: "Cartões amarelos",
//   [MatchStatisticsTypeEnum.RED_CARDS]: "Cartões vermelhos",
//   [MatchStatisticsTypeEnum.GOALKEEPER_SAVES]: "Defesas importantes",
//   [MatchStatisticsTypeEnum.TOTAL_PASSES]: "Passes",
//   [MatchStatisticsTypeEnum.PASSES_ACCURATE]: "Porcentagem de passes corretos",
// };
