export const LeaguesEnum = {
  BRASILEIRAO_SERIE_A: 71,
};

export const TeamIdEnum = {
  ATHLETICO_PARANAENSE: 134,
  ATLETICO_GOIANENSE: 144,
  ATLETICO_MG: 1062,
  BAHIA: 118,
  BOTAFOGO: 120,
  BRAGANTINO: 794,
  CORINTHIANS: 131,
  CRICIUMA: 140,
  CRUZEIRO: 135,
  CUIABA: 1193,
  FLAMENGO: 127,
  FLUMINENSE: 124,
  FORTALEZA: 154,
  GREMIO: 130,
  INTERNACIONAL: 119,
  JUVENTUDE: 152,
  PALMEIRAS: 121,
  SAO_PAULO: 126,
  VASCO_DA_GAMA: 133,
  VITORIA: 136,
};

export const teamNameMap = {
  [TeamIdEnum.ATHLETICO_PARANAENSE]: "Athletico Paranaense",
  [TeamIdEnum.ATLETICO_GOIANENSE]: "Atletico-GO",
  [TeamIdEnum.ATLETICO_MG]: "Atletico-MG",
  [TeamIdEnum.BAHIA]: "Bahia",
  [TeamIdEnum.BOTAFOGO]: "Botafogo",
  [TeamIdEnum.BRAGANTINO]: "Bragantino",
  [TeamIdEnum.CORINTHIANS]: "Corintians",
  [TeamIdEnum.CRICIUMA]: "Criciuma",
  [TeamIdEnum.CRUZEIRO]: "Cruzeiro",
  [TeamIdEnum.CUIABA]: "Cuiabá",
  [TeamIdEnum.FLAMENGO]: "Flamengo",
  [TeamIdEnum.FLUMINENSE]: "Fluminense",
  [TeamIdEnum.FORTALEZA]: "Fortaleza",
  [TeamIdEnum.GREMIO]: "Gremio",
  [TeamIdEnum.INTERNACIONAL]: "Internacional",
  [TeamIdEnum.JUVENTUDE]: "Juventude",
  [TeamIdEnum.PALMEIRAS]: "Palmeiras",
  [TeamIdEnum.SAO_PAULO]: "São Paulo",
  [TeamIdEnum.VASCO_DA_GAMA]: "Vasco da Gama",
  [TeamIdEnum.VITORIA]: "Vitória",
};
